### ISSUE TITLE
`func (*Sling) Receive` error return

### ISSUE THREAD

**Issue by diemonster** [dghubble/sling#5]
When calling Receive method i.e. `statuses.New().Get("show.json").QueryStruct(params).Receive(tweet)`, error should return `http.Response` `Status` (or something similar) if URL is unavailable, versus JSON Unmarshal error. 

Not sure if other Sling methods are affected by this behavior?

**Comment by dghubble** [comment]
Currently, `Receive(v interface{})` and `Do(req *http.Request, v interface{})` both consider non-2XX responses valid (as noted [here](https://github.com/dghubble/sling/blob/master/sling.go#L326)) and attempt to decode the `resp.Body` into `v`. The returned error indicates that this JSON decoding fails so I'm not sure what would make a better error if done this way.

However, Sling v1 (see branch `dev`) will address the final Roadmap item "support JSON error responses" since most APIs provide different JSON for successes or failures. `Receive(v interface{})` is anticipated to become `Receive(successV, failureV interface{})`. 2XX responses will be decoded into `successV` and non-2XX responses will be decoded into `failureV`.

```go
type GithubError struct {
    Message string `json:"message"`
    Errors  []struct {
        Resource string `json:"resource"`
        Field    string `json:"field"`
        Code     string `json:"code"`
    } `json:"errors"`
    DocumentationURL string `json:"documentation_url"`
}
```

```go
issues := new([]Issue)
githubError := new(GithubError)
resp, err := githubBase.New().Get(path).QueryStruct(params).Receive(issues, githubError)
```

This won't completely address your concern though. Some APIs (like Github) return error JSON for all invalid requests [example](https://api.github.com/invalid) while others just return a [generic HTTP 404](https://api.twitter.com/1.1/invalid). The later case is often an error on the part of the API client lib.

To completely address your concern I think gating decoding by `Content-Type: application/json` is needed.

**Comment by diemonster** [comment]
The code in `dev` is great --- `Receive(successV, failureV interface{})` is a nice pattern. We ended up wrapping `Receive` with a helper function similar to the `ReceiveSuccess` method, but slightly differently as we needed additional error logging. At any rate, thanks for patching so quickly, nice work! :heart_eyes:

**Comment by dghubble** [comment]
With #7 Content-Type will be checked before attempting to JSON decode into values.
